Make m_imageRenderingSet unsigned
Compiling qtsvg for webassembly, the compiler throws an error:

svgstyle.cpp:58:25: error: implicit truncation from 'int' to
a one-bit wide bit-field changes value from 1 to -1
[-Werror,-Wsingle-bit-bitfield-constant-conversion]

which makes sense, given that a signed integer of bit width 1
doesn't really add up in any meaningful way.

A simple solution is to simply make the type unsigned.

Change-Id: I49c6019bc48e98ce953f945a24cab7a32dd6f37a
Pick-to: 6.5
Reviewed-by: Edward Welbourne <edward.welbourne@qt.io>