Fix build with -no-feature-cssparser
qt5/qtsvg/src/svg/qsvghandler_p.h:23:10: fatal error: private/qcssparser_p.h: No such file or directory
   23 | #include "private/qcssparser_p.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~

Change-Id: I058920a57e0d452c2b67ee69e32f363bc7587a74
Reviewed-by: Volker Hilsheimer <volker.hilsheimer@qt.io>
(cherry picked from commit 521153c7208205b82554fd2e8a74b9ab09f9d6fc)
Reviewed-by: Qt Cherry-pick Bot <cherrypick_bot@qt-project.org>