Fix maybe-uninitialized warning
error: 'r' may be used uninitialized [-Werror=maybe-uninitialized]
and same with g and b. So init them where they are defined.
Amends 425366a7c0ee77f53b38c850e923822626cee1f1

Change-Id: I8cb3a280a07a2b69873bc0cbfa02ab1344b02eb1
Reviewed-by: Hatem ElKharashy <hatem.elkharashy@qt.io>
Reviewed-by: Magdalena Stojek <magdalena.stojek@qt.io>