Fix warnings found by clang: unused private members
Classes with no friends should use all its private members. Otherwise,
they just take up space for no good reason -- unless it's a
placeholder for future use (binary compatibility). These are also
private classes, so BC does not apply.

qsvgstyle_p.h:198:9: error: private field 'm_colorRendering' is not used [-Werror,-Wunused-private-field]
qsvgstyle_p.h:693:25: error: private field 'm_by' is not used [-Werror,-Wunused-private-field]

Change-Id: I6aee61b2ba195b251cd1896e41948cc42ff68c46
Reviewed-by: Robin Burchell <robin+qt@viroteck.net>