Fix a bad virtual override
Problem found by Clang. It took me a while to notice the missing "s"

qsvggenerator.cpp:177:10: error: 'QSvgPaintEngine::drawImage' hides overloaded virtual function [-Werror,-Woverloaded-virtual]

Change-Id: If95e299f12dea62344efee4a2c542b6474314b0e
Reviewed-by: Gunnar Sletta <gunnar.sletta@digia.com>